config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "lyte#index"
  resources :lytes
  resources :user_tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snippet.rb
class Snippet < ApplicationRecord
    validates :description, presence: true
    validates :body, presence: true
    has_many :user_tag_snippets
    has_many :user_tags, through: :user_tag_snippets
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
    validates :label, presence: true
    has_many :user_tag_snippets
    has_many :snippets, through: :user_tag_snippets
end

app/models/user_tag_snippet.rb
class UserTagSnippet < ApplicationRecord
    belongs_to :user_tag
    belongs_to :snippet

    self.table_name = "user_tag_snippet"
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lyte_controller.rb
class LyteController < ApplicationController

  def index
    @snippets = Snippet.all.limit(100).each
  end

end

app/controllers/user_tags_controller.rb
class UserTagsController < ApplicationController

  def show
    @snippets = UserTag.find(params[:id]).snippets.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">*</a></h1>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="active"><a href="#">Right Button Active</a></li>
        <li class="has-dropdown">
          <a href="#">Right Button Dropdown</a>
          <ul class="dropdown">
            <li><a href="#">First link in dropdown</a></li>
            <li class="active"><a href="#">Active link in dropdown</a></li>
          </ul>
        </li>
      </ul>
      <!-- Left Nav Section -->
      <ul class="left">
        <li><a href="#">Left Nav Button</a></li>
      </ul>
    </section>
  </nav>
  <div class="medium-3 columns">
    <ul class="side-nav">
    <form>
      <input type="text" style="width:100px;height:25px;font-size:10px;"/>
    </form>
    <% UserTag.all.each do |tag| %>
      <li><%= link_to tag.label, user_tag_path(tag.id) %></a></li>
    <% end %>
    </ul>
  </div>
  <div class="medium-9 columns">
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/lyte/index.html.erb
<% UserTag.all.each do |tag| %>
<h1><%= tag.label %></h1>

<% tag.snippets.each do |snippet| %>

<div><%= snippet.description %></div>

<% end %>

<% end %>

app/views/shared/_snippet_list.html.erb
<% @snippets.each do | s | %>
<div style='margin-bottom: 5px'>
  <div>
  <%= s.description %>
  </div>
  <pre><%= s.body %></pre>
</div>
<% end %>

app/views/user_tags/show.html.erb
<%= render partial: '/shared/snippet_list', locals: { snippets: @snippets} %>